export const ADD_EDUCATION_DESCRIPTION = "ADD_EDUCATION_DESCRIPTION"
export const ADD_EDUCATION_TITLE = "ADD_EDUCATION_TITLE"
export const ADD_EDUCATION = "ADD_EDUCATION"
export const SET_EDUCATION_POSITION = "SET_EDUCATION_POSITION"
export const DELETE_EDUCATION = "DELETE_EDUCATION"

export const EDUCATION_POSITION_CHANGED = "EDUCATION_POSITION_CHANGED";