export const ADD_PROFILE_LOADING = "ADD_PROFILE_LOADING"
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING"
export const DELETE_PROFILE_LOADING = "DELETE_PROFILE_LOADING"

export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS"

export const ADD_PROFILE_ERROR = "ADD_PROFILE_ERROR"
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR"
export const DELETE_PROFILE_ERROR = "DELETE_PROFILE_ERROR"

export const GET_PROFILE = "GET_PROFILE"